language: android

android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra-android-support

env:
    matrix:
      - ANDROID_SDKS=android-19 ANDROID_TARGET=android-19

before_install:

  #################################################
  ########## maven-android-sdk-deployer ###########
  #################################################

  # Checkout maven-android-sdk-deployer
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git

  # Install android maven repository
  - cd $PWD/maven-android-sdk-deployer/platforms/$ANDROID_TARGET
  - mvn  install -N --quiet
  - cd -

  # Install locally compatibility-v4
  - cd $PWD/maven-android-sdk-deployer/extras/compatibility-v4
  - mvn install -N --quiet
  - cd -
